name: Java CI and Publish

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build and test
        run: mvn -B -e -DskipTests=false clean verify

  publish:
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')) ||
      (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17 and configure Maven for OSSRH
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # diagnostics + explicit settings
      - name: Check OSSRH secrets availability
        run: |
          if [ -z "${{ secrets.OSSRH_USERNAME }}" ] || [ -z "${{ secrets.OSSRH_PASSWORD }}" ]; then
            echo "ERROR: OSSRH_USERNAME or OSSRH_PASSWORD is not available to this run."
            exit 1
          else
            echo "OSSRH secrets are present."
          fi
      
      - name: Deploy to OSSRH (release or snapshot)
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          # For tag pushes (vX.Y.Z) perform a release deploy; otherwise deploy snapshots to OSSRH snapshot repo
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            mvn -B -Prelease clean deploy -DskipTests
          else
            mvn -B -DskipTests clean deploy
          fi